### PR TITLE
Several small improvements

### PR DESCRIPTION
**Pull request by JonasGroeger**
Hi @me-vlad,

I'm happily using your script and wanted to give something back :)

I'll have another pull request ready where users can specify if they want to use `pass` or `gopass` in the `ansible.cfg` file instead of editing the script.

### CODE REVIEW

**Comment by JonasGroeger** [comment]
Can I do something to get this merged? :) If you don't have the time to review its all good.

**Comment by me-vlad** [comment]
Hi Jonas, thanks for you help, I'll check and test your commits next days. It will be fine to separate cosmetic changes (typos, styling) from refactoring

**Comment by JonasGroeger** [comment]
> It will be fine to separate cosmetic changes (typos, styling) from refactoring.

I'm not sure what you mean. I tried to do that in my commits :)

**Comment by me-vlad** [comment]
> > It will be fine to separate cosmetic changes (typos, styling) from refactoring.
> 
> I'm not sure what you mean. I tried to do that in my commits :)

I mean that all styling changes in a separate PR I can merge without deeper testing

**Pull request closed without merging**
